import 'package:prayer_time_gi/Screens/MenuPages/Esmail_Husna/EsmaScreen.dart';

class Esma {
  final String isimTurce;

  final String anlam;

  Esma(this.isimTurce, this.anlam);

  static var esmaTileListe = [
    EsmaTile("ALLAH", "bütün gözəl sifətləri özündə ehtiva edən", 1),
    EsmaTile("ƏL-CƏLİL", "cəlallı", 2),
    EsmaTile("ƏL-QÜDDUS", "müqəddəs", 3),
  EsmaTile("ƏL-AXİR", "hər şeydən sonra mövcud olacaq", 4),
  EsmaTile("ƏS-SƏMİ", "hər şeyi eşidən", 5),
  EsmaTile("ƏL-BƏSİR", "hər şeyi görən", 6),
  EsmaTile("ƏL-QƏDİR ", "hər şeyə qüdrəti çatan", 7),
  EsmaTile("ƏL-ƏVVƏL", "hər şeydən əvvəl mövcud olmuş", 8),
  EsmaTile("ƏL-QAHİR", "zalımları qəhr edən", 9),
  EsmaTile("ƏL-ƏLİYY", "yüksək, uca", 10),
  EsmaTile("ƏL-Ə'LA", "ən yüksək, ən uca", 11),
  EsmaTile("ƏL-BAQİ", "əbədi, daimi, qaları", 12),
  EsmaTile("ƏL-BƏDİ", "həmişə ixtira edən", 13),
  EsmaTile("ƏL-BARİ", "yaradıcı", 14),
  EsmaTile("ƏL-ƏKRƏM", "ən kəramətli", 15),
  EsmaTile("ƏZ-ZAHİR", "aşkardakıları bilən", 16),
  EsmaTile("ƏL-BATİN", "gizlindəkiləri bilən", 17),
  EsmaTile("ƏL-HƏYY", "diri olan", 18),
  EsmaTile("ƏL-HƏKİM", "çox hikmətli", 19),
  EsmaTile("ƏL-ƏLİM", "hər şeyi bilən, çox elmli", 20),
  EsmaTile("ƏL-HƏLİM", "çox mülayim", 21),
  EsmaTile("ƏL-HƏFİZ", "ən yaxşı qoruyucu, mühafizəçi", 22),
  EsmaTile("ƏL-HƏQQ", "həqiqət", 23),
  EsmaTile("ƏL-HƏSİB", "hər şeyi hesaba alan", 24),
  EsmaTile("ƏL-HƏMİD", "həmd edilən (yaxud həmdə layiq)", 25),
  EsmaTile("ƏL-HƏFİYY", "öz yaratdıqlarını çox sevən", 26),
  EsmaTile("ƏN-NUR", "nurun qaynağı", 27),
  EsmaTile("ƏR-RƏBB", "bəsləyən, pərvəriş edən", 28),
  EsmaTile("ƏR-RAHMƏN", "çox mərhəmətli", 29),
  EsmaTile("ƏR-RƏHİM", "həmişə mərhəmətli", 30),
  EsmaTile("ƏR-RƏUF", "mehriban, şəfqətli", 31),
  EsmaTile("ƏR-RAİ", "hər şeyi görən", 32),
  EsmaTile("ƏR-RƏQİB", "nəzarətçi, keşikçi", 33),
  EsmaTile("ƏZ-ZARİ", "bəndələrinin aqibətini müəyyən edən", 34),
  EsmaTile("ƏS-SƏLAM", "hər təhlükədən salamatlığa çıxaran", 35),
  EsmaTile("ƏR-RƏZZAQ", "ruzi verən", 36),
  EsmaTile("ƏL-MÖ'MİN", "iman bəxş edən (yaxud iman bəslənilən)", 37),
  EsmaTile("ƏL-MÜHƏYMİN", "himayə edən", 38),
  EsmaTile("ƏL-ƏZİZ", "çox izzətli", 39),
  EsmaTile("ƏL-CƏBBAR", "zalımlara əziyyət verən", 40),
  EsmaTile("ƏL-MÜTƏKƏBBİR", "məqamı uca tutulan, böyüdülən", 41),
  EsmaTile("ƏS-SƏYYİD", "ağa, başçı", 42),
  EsmaTile("ƏŞ-ŞƏHİD", "hər şeyə şahid olan və nəzarətçi olan", 43),
  EsmaTile("ƏS-SADİQ", "sədaqətli, doğrucul", 44),
  EsmaTile("ƏT-TAHİR", "pak, saf", 45),
  EsmaTile("ƏL-ĞƏNİYY", "ehtiyacsız, varlı", 46),
  EsmaTile("ƏL-ĞİYAS", "köməkçi", 47),
  EsmaTile("ƏL-FATİR", "yaradan, vucuda gətirən", 48),
  EsmaTile("ƏL-FƏRD", "tək, yeganə", 49),
  EsmaTile("ƏL-FƏTTAH", "çətinlikləri həll edən", 50),
  EsmaTile("ƏL-FALİQ", "dan yerini yaran, parçalayan", 51),
  EsmaTile("ƏL-QƏDİM", "olmadığı zaman təsəvvürə gəlməyən", 52),
  EsmaTile("ƏL-MƏLİK", "mülk sahibi", 53),
  EsmaTile("ƏL-QƏVİYY", "çox qüvvətli", 54),
  EsmaTile("ƏL-QƏRİB", "çox yaxın", 55),
  EsmaTile("ƏL-QƏYYUM", "dayanıqlı, sarsılmaz, sabit", 56),
  EsmaTile("ƏL-QABİZ", "sıxan, canları alan və ya qəbz edən", 57),
  EsmaTile("ƏL-BASİT", "açıb sərən və ya səxavətli", 58),
  EsmaTile("QAZİYUL-HACAT", "hökm verən, ehtiyacları həll edən", 59),
  EsmaTile("ƏŞ-ŞAFİ", "şəfa verən, sağaldan", 60),
  EsmaTile("ƏL-MƏCİD", "şan-şöhrətli, əzəmətli, ulu", 61),
  EsmaTile("ƏL-VƏLİYY (ƏL-MÖVLA)", "dost (ağa, sərvər)", 62),
  EsmaTile("Əl-LƏTİF", "lütf edən", 63),
  EsmaTile("ƏL-MƏNNAN", "bəndələrinə çox ehsan edən", 64),
  EsmaTile("ƏL-MÜHİT", "hər şeyi əhatə edən", 65),
  EsmaTile("ƏL-MÜBİN", "hər şeyi bəyan edib aşkarlayan", 66),
  EsmaTile("ƏL-MÜQİT (ƏL-MÜĞİS)", "müqəddəs", 67),
  EsmaTile("ƏL-MUSƏVVİR", "hər şeyi formaya salan", 68),
  EsmaTile("ƏL-KƏRİM", "çox kəramətli", 69),
  EsmaTile("ƏL-KƏBİR", "çox böyük", 70),
  EsmaTile("ƏL-KAFİ", "kifayət edən, hər şeyə bəs edən", 71),
  EsmaTile("KAŞİFÜZ-ZÜRR", "zərərin üstünü açıb ifşa edən", 72),
  EsmaTile("ƏL-VİTR", "tək-tənha", 73),
  EsmaTile("ƏL-ƏZİM", "əzəmətli", 74),
  EsmaTile("ƏL-VƏHHAB", "nemət bağışlayan", 75),
  EsmaTile("ƏN-NASİR", "köməkçi, yardımçı", 76),
  EsmaTile("ƏL-VASE", "çox əhatəli, geniş", 77),
  EsmaTile("ƏL-VƏDUD", "bəndələrini çox sevən", 78),
  EsmaTile("ƏL-HADİ", "hidayət edən, doğru yol göstərən", 79),
  EsmaTile("ƏL-VƏFİYY", "vəfalı, sadiq", 80),
  EsmaTile("ƏL-VEKİL", "himayəçi", 81),
  EsmaTile("ƏL-VARİS", "Mülkün gerçek sahibi", 82),
  EsmaTile("ƏL-BİRR", "yaxşı sifətlərin sahibi", 83),

  EsmaTile("ƏL-BAİS", "qiyamətdə ölüləri dirildəcək zat", 84),
  EsmaTile("ƏT-TƏVVAB", "tövbələri qəbul edən", 85),
  EsmaTile("ƏL-CAVAD", "səxavətli", 86),
  EsmaTile("ƏL-XƏBİR", "hər şeydən xəbərdar olan", 87),
  EsmaTile("ƏL-XALİQ", "xəlq edən, yaradan", 88),
  EsmaTile("XEYRUN-NASİRİN", "ən yaxşı yardımçı", 89),
  EsmaTile("ƏD-DƏYYAN", "hesabat gününün sahibi, hakim", 90),
  EsmaTile("ƏŞ-ŞƏKÜR", "şükr edilən (yaxud şükrə layiq)", 91),
  EsmaTile("ƏS-SANE", "yaradıcı", 92),
  EsmaTile("ƏL-ƏDL", "hesabat gününün sahibi, hakim", 93),
  EsmaTile("ƏL-ĞƏFUR", "əfv edən, bağışlayan", 94),
    EsmaTile("ƏL-ƏFFÜV", "günahları bağışlayan", 95),

    EsmaTile( "ƏL-CƏLİL", "cəlallı", 96),
    EsmaTile("ƏL-VAHID", "yeganə" , 97),
    EsmaTile("ƏL-ƏHƏD", "bənzərsiz", 98),
    EsmaTile("ƏS-SAMƏD", "ehtiyacsız", 99),







  ];
}