
class Esma {


  static var esmaTileListe = [
 "ALLAH c.c.", "Ər-Rəhmân","Ər-Rahim ", "Əl-Məlik","Əl-Quddus ","Əs-Səlâm ","Əl-Mü’min ","Əl-Mühəymin ","Əl-Əziz ","Əl-Cəbbâr ","Əl-Mütəkəbbir ",
    "Əl-Xâliq ","Əl-Bârî ","Əl-Musəvvir ","Əl-Gaffâr ","Əl-Kahhâr ","Əl-Vəhhâb ","Ər-Rəzzâk ","Əl-Fəttâh ","Əl-Alîm ","Əl-Kâbıd ","Əl-Bâsıt ",
    "Əl-Hâfıd ","Ər-Râfî","Əl-Muiz","Əl-Muzil ","Es-Səmî ","Əl-Basîr ","Əl-Hakem ","Əl-Adl",
        "Əl-Lətîf ",
    "Əl-Həbîr ","Əl-Həlîm ","Əl-Əzîm ","Əl-Gafûr ","Əş-Şəkûr ","Əl-Əliyy ","Əl-Kəbîr ","Əl-Hafîz","Əl-Mukît ","Əl-Hasîb ","Əl-Cəlîl ","Əl-Kərîm ","Ər-Rakîb ",
    "Əl-Mücîb","Əl-Vâsî ","Əl-Hakîm ","Əl-Vədûd ","Əl-Məcîd ","Əl-Bâis ","Əş-Şəhîd ","Əl-Hakk ","Əl-Vəkîl ","Əl-Kaviyy ","Əl-Mətîn ","Əl-Veliyy ","Əl-Həmîd ",
    "Əl-Muhsî","Əl-Mübdi","Əl-Muid","Əl-Muhyî","Əl-Mümît","Əl-Hayy" ,
    "Əl-Qəyyûm ","Əl-Vâcid ","Əl-Mâcid ","Əl-Vâhid ","Əs-Saməd ","Əl-Qâdir ","Əl-Muqtədir ","Əl-Muqəddim ","Əl-Muahhir ","Əl-Əvvəl ","Əl-Âxir ","Əz-Zâhir ","Əl-Bâtın ",
    "Əl-Vâlî ","Əl-Müteâlî ","Əl-Bərr ","Ət-Təvvâb ","Əl-Müntakim","Əl-Afüvv ","Ər-Raûf","Mâlikü’l-Mülk	 ","Zü’l- Cəlal-i vəl-İkram","Əl-Muksıt ","Əl-Câmî ","Əl-Ganîyy ",
    "Əl-Muğnî ","Əl-Mânî ","Əd-Dâr ","Ən-Nâfi ","Ən-Nûr ",
  "Əl-Hâdî", "Əl-Bədî", "Əl-Bâki", "Əl-Vâris", "Ər-Rəşid", "Əs-Sabûr",
  ];
  static List<String> arabItem = [
    "الله",
    "الرَّحْمَنُ",
    "الرَّحِيمُ",
    "الْمَلِكُ",
    "الْقُدُّوسُ",
    "السَّلاَمُ",
    "الْمُؤْمِنُ",
    "الْمُهَيْمِنُ",
    "الْعَزِيزُ",
    "الْجَبَّارُ",
    "الْمُتَكَبِّرُ",
    "الْخَالِقُ",
    "الْبَارِئُ",
    "الْمُصَوِّرُ",
    "الْغَفَّارُ",
    "الْقَهَّارُ",
    "الْوَهَّابُ",
    "الرَّزَّاقُ",
    "الْفَتَّاحُ",
    "اَلْعَلِيْمُ",
    "الْقَابِضُ",
    "الْبَاسِطُ",
    "الْخَافِضُ",
    "الرَّافِعُ",
    "الْمُعِزُّ",
    "المُذِلُّ",
    "السَّمِيعُ",
    "الْبَصِيرُ",
    "الْحَكَمُ",
    "الْعَدْلُ",
    "اللَّطِيفُ",
    "الْخَبِيرُ",
    "الْحَلِيمُ",
    "الْعَظِيمُ",
    "الْغَفُورُ",
    "الشَّكُورُ",
    "الْعَلِيُّ",
    "الْكَبِيرُ",
    "الْحَفِيظُ",
    "المُقيِت",
    "الْحسِيبُ",
    "الْجَلِيلُ",
    "الْكَرِيمُ",
    "الرَّقِيبُ",
    "الْمُجِيبُ",
    "الْوَاسِعُ",
    "الْحَكِيمُ",
    "الْوَدُودُ",
    "الْمَجِيدُ",
    "الْبَاعِثُ",
    "الشَّهِيدُ",
    "الْحَقُّ",
    "الْوَكِيلُ",
    "الْقَوِيُّ",
    "الْمَتِينُ",
    "الْوَلِيُّ",
    "الْحَمِيدُ",
    "الْمُحْصِي",
    "الْمُبْدِئُ",
    "الْمُعِيدُ",
    "الْمُحْيِي",
    "اَلْمُمِيتُ",
    "الْحَيُّ",
    "الْقَيُّومُ",
    "الْوَاجِدُ",
    "الْمَاجِدُ",
    "الْواحِدُ",
    "اَلاَحَدُ",
    "الصَّمَدُ",
    "الْقَادِرُ",
    "الْمُقْتَدِرُ",
    "الْمُقَدِّمُ",
    "الْمُؤَخِّرُ",
    "الأوَّلُ",
    "الآخِرُ",
    "الظَّاهِرُ",
    "الْبَاطِنُ",
    "الْوَالِي",
    "الْمُتَعَالِي",
    "الْبَرُّ",
    "التَّوَابُ",
    "الْمُنْتَقِمُ",
    "العَفُوُّ",
    "الرَّؤُوفُ",
    "مَالِكُ الْمُلْكِ",
    "ذُوالْجَلاَلِ وَالإكْرَام",
    "الْمُقْسِطُ",
    "الْجَامِعُ",
    "الْغَنِيُّ",
    "الْمُغْنِي",
    "اَلْمَانِعُ",
    "الضَّارَّ",
    "النَّافِعُ",
    "النُّورُ",
    "الْهَادِي",
    "الْبَدِيعُ",
    "اَلْبَاقِي",
    "الْوَارِثُ",
    "الرَّشِيدُ",
    "الصَّبُورُ"
  ];

  static var mena = [
    "Bütün isim ve sifətlərı özündə toplayan",
    "Rəhmətiylə muamələ edən",
    "Mərhəmət edən, bağışlayan",
    "Mülkün gərçək sahibi, mülk ve səltənəti dəvamlı olan.	",
    "Hər cür əksiklik və ayıblardan uzaq olan",
    "Qullarını salamatlığa çıxaran",
    "Könüllərdə iman ışığı oyandıran",
    "Gözətən ve qoruyan",
    "Məğlub edilməsi əsla mümkün olmayan",
    "İstədiğini mütləq edən, dilədiğinə müqtədir olan",
    "Hər şeydə böyüklüğünü göstərən",
    "Hər şeyi yoxdan var edən",
    "Hər şeyi uyğun bir tərzdə ve birbirinə uyğun yaradan",
    "Hər şeyə bir forma və xüsusiyyət verib təsvir edən",
    "Qullarının günahlarını örtən, günahlarını bağışlayan",
    "Her şeyə, hər istədiğini edəcək sürətdə galib ve hakim olan",
    "Ehsanı bol olan",
    "Bütün məxluqatın ruzisini verən və ehtiyyacını qarşılayan",
    "Hər cür çətinlikləri asanlaşdıran, sıxıntıdan qurtaran",
    "Hər şeyi ən incə nöqtəsinə qədər bilən, elmi əbədi və əzəli olan",
    "Dilədiğinə sıxıntı verən, sıxan",
    "Dilədiğinə bolluq verən, açan, genişlədən",
    "Yuxarıdan aşağıya indirən, alçaldan",
    "Yuxarı qaldıran, yüksəldən",
    "İzzət verib ağırlayan",
    "Zillətə düşüren",
    "Hər şeyi eşidən",
    "Hər şeyi görən",
    "Hər işde hikmət və ədalətlə hökmedən",
    "Son dərəcə ədalətli olan",
    "İşlərin bütün incəliklərini bilən",
    "Hər şeyin iç üzündən, gizli tərəfindan xəbərdar olan",
    "Yumuşaq davranan, hilmi çox olan",
    "Çox əzəmətli və böyük olan",
    "Çox bağışlayan, məğfirəti çox olan",
    "Öz rizası üçün edilən yaxşı işləri, artıqlamasıyla mükafatlandıran",
    "Çox uca, çox yüksək olan",
    "Böyüklüyünün həddi hüdudu olmayan",
    "Edilən işləri bütün təfsilatıyla, ayrıntılarıyla tutan",
    "Yaradılmış her şeyin azüqəsini verən",
    "Hərkəsin həyatı boyunca etdiklərinin hesabını soruşan",
    "Əzəmət sahibi olan, ululuq sahibi olan",
    "Çox ikram edən. Kərəmi və məğfirəti bol olan",
    "Bütün varlıqlar üzərində gözətçi olan",
    "Dua edənlərin dualarını qəbul edən, istəklərini verən",
    "Lütfü bol olan",
    "Əmirləri, kəlamı və bütün işləri hikmətli olan",
    "Yaxşı qullarını sevən, sevilməyə və dostluğa haqqıyla layiq olan",
    "Şanı çox böyük və çox yüksək olan",
    "Ölüləri dirildib qəbirlərindən çıxaran",
    "Hər zaman və hər yerdə hazır və nazir olan",
    "Vacibul vücud olan, varlığı heç dəyişmədən duran",
    "İşlərini özünə buraxanların işini düzəldən və hər şeyin yaxşısını təmin eden",
    "Çox quüvvətli. Çox güclü olan",
    "Çok sağlam olan",
    "Yaxşı qullarına, gerçək möminlərə dost olan",
    "Hər cür həmd və tərifə layiq olan",
    "İstisnasız hər şeyin tək tək sayısını bilən",
    "Bütün məxluqatı maddəsiz və bənzərsiz olaraq ilk başdan yaradan",
    "Yaradılmışları yox etdikdən sonra təkrar yaradan",
    "Əhya edən, dirildən, can bağışlayan, sağlıq verən",
    "Ölümü yaradan, öldürən",
    "Diri, tam və mükəmməl mənasıyla həyat sahibi",
    "Göyləri, yeri və hər şeyi tutan",
    "İstədiğini, istədiyi vaxt tapan",
    "Kərəmi bol olan",
    "Tək olan",
    "Sığınacaq tək dayaq olan",
    "Hər şeyə gücü yetən, hər istədiyini etməyə qâdir olan",
    "Qüvvət və qüdrət sahibləri üzərində istədiyi kimi təsərruf edən",
    "İstədiyini iləri çəkib, önə alan",
    "İstediğini geri koyan, arkaya bırakan.	",
    "Başlanğıcı olmayan, ilk olan",
    "Sonu olmayan, son olan",
    "Açıqca bilinən, əşkar olan",
    "Gizli olan",
    "Hər şeyi tək başına idarə eden",
    "Ağlın mümkün gördüyü hər şeydən, hər hâl və hərəkətdən münəzzəh olan",
    "Qullarına yaxşılıq və ehsanı, nemətləri bol olan",
    "Tövbələri qəbul edən",
    "Günahkarları ədalətiylə cəzalandırıb intiqam alan",
    "Əffi və rəhməti çox olan, bağışlayan",
    "Çox mərhəmət göstərən, lütf və mərhəmətlə çox esirgeyen",
    "Mülkün əbədi sahibi olan",
    "Hər cür böyüklüyün, hər cür kərəmin sahibi olan",
    "Bütün işləri birbirinə uyğun və səviyyədə edən",
    "İstədiyini istədiyi zaman istədiyi yerdə toplayan",
    "Çox zəngin olan",
    "İstədiyini zəngin eden",
    "Bəzi şeylərin meydana gəlməsinə icazə verməyən, mane olan",
    "Ələm və ziyan verəcək şeyləri yaradan, hüsrana uğradan",
    "Xeyir və mənfəət verəcək şeyləri yaradan",
    "Aləmləri nurlandıran",
    "Hidayətə və doğru yola yönəldən",
    "Əmsalsız, misilsiz, heyrət verici neçə neçə âləmlər icad edən",
    "Varlığının sonu mövcud olmayan, əbədi olan",
    "Sərvətlərin gerçək sahibi olan",
    "Bütün işleri əzəli təqdirinə uyğun bir nizam və hikmət üzrə sonuna çatdıran",
    "Çox səbirli olan",


  ];

}